# Generated by Django 5.2.10 on 2026-05-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trading', '0004_session_based_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FnOInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying', models.CharField(max_length=20)),
                ('instrument_type', models.CharField(choices=[('CE', 'Call'), ('PE', 'Put'), ('FUT', 'Future')], max_length=3)),
                ('expiry', models.DateField()),
                ('strike', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lot_size', models.PositiveIntegerField(default=100)),
            ],
            options={
                'unique_together': {('underlying', 'instrument_type', 'expiry', 'strike')},
            },
        ),
        migrations.CreateModel(
            name='FnOOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('lots', models.IntegerField()),
                ('executed_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('status', models.CharField(choices=[('EXECUTED', 'Executed'), ('REJECTED', 'Rejected')], default='EXECUTED', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper_trading.fnoinstrument')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fno_orders', to='paper_trading.paperportfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FnOPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lots', models.IntegerField()),
                ('avg_entry_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('last_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('margin_blocked', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper_trading.fnoinstrument')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fno_positions', to='paper_trading.paperportfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'instrument')},
            },
        ),
    ]
